package candidate

object Coefficients {
  val HEIGHT_FRACTION = 0.3
  val PAGE_FRACTION = 0.3
  val BOLD_FRACTION = 0.5
  val LOCATION_FRACTION = 0.5
  val PHRASE_TYPE_FRACTION = 0.5
  val PANK_FRACTION = 0.5
  val EURO_SIGN_FRACTION = 0.2
  val DOUBLE_NUMBER_FRACTION = 0.3
  val BELOW_FRACTION = 0.8
  val BIGGER_SUM_FRACTION = 0.8
  val NORMAL_TOTAL_LINE = 1.5
}